#!/bin/bash
#SBATCH --exclusive
#SBATCH --time=0-00:05:00
#SBATCH --mail-user=btasseff@lanl.gov
#SBATCH --mail-type=END
#SBATCH --output=/dev/null --error=/dev/null

# Set important environment variables first.
source .profile

# Read in the experiment CSV file and separate values by comma.
EXPERIMENT_CSV_PATH="data/experiments/preprocessing/NONE.csv"
LINE_NUMBER=${SLURM_ARRAY_TASK_ID}
LINE_STRING=$(sed "${LINE_NUMBER}q;d" ${EXPERIMENT_CSV_PATH})
IFS=',' read -a PARAMETER_ARRAY <<< "${LINE_STRING}"

# Set up variables for notational ease.
INSTANCE_PATH=${PARAMETER_ARRAY[0]}
MODIFICATION_PATH=${PARAMETER_ARRAY[1]}
RESULT_PATH=${PARAMETER_ARRAY[2]}
LOG_PATH=${PARAMETER_ARRAY[3]}

# Get the sysimage path.
SYSIMAGE_PATH="scripts/precompilation/WaterModels.so"

# Execute the script.
julia \
    -J${SYSIMAGE_PATH} \
    scripts/execution/preprocessing-none.jl \
    --input_path ${INSTANCE_PATH} \
    --modification_path ${MODIFICATION_PATH} \
    --output_path ${RESULT_PATH} \
    &> ${LOG_PATH}
